/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_matrix4f_cardcutter_platformspecific_MSWordInteractor */

#ifndef _Included_me_matrix4f_cardcutter_platformspecific_MSWordInteractor
#define _Included_me_matrix4f_cardcutter_platformspecific_MSWordInteractor
#ifdef __cplusplus
extern "C" {
	#endif
	/*
	 * Class:     me_matrix4f_cardcutter_platformspecific_MSWordInteractor
	 * Method:    getWordWindows
	 * Signature: ()[Ljava/lang/String;
	 */
	JNIEXPORT jobjectArray JNICALL Java_me_matrix4f_cardcutter_platformspecific_MSWordInteractor_getWordWindows
	(JNIEnv *, jobject);

	/*
	 * Class:     me_matrix4f_cardcutter_platformspecific_MSWordInteractor
	 * Method:    selectWordWindow
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_me_matrix4f_cardcutter_platformspecific_MSWordInteractor_selectWordWindow
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     me_matrix4f_cardcutter_platformspecific_MSWordInteractor
	 * Method:    setShiftKeyState
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_me_matrix4f_cardcutter_platformspecific_MSWordInteractor_setShiftKeyState
	(JNIEnv *, jobject, jboolean);

	#ifdef __cplusplus
}
#endif
#endif
