/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_sohamgovande_cardr_platformspecific_WinMSWordInteractor */

#ifndef _Included_me_sohamgovande_cardr_platformspecific_WinMSWordInteractor
#define _Included_me_sohamgovande_cardr_platformspecific_WinMSWordInteractor
#ifdef __cplusplus
extern "C" {
	#endif
	/*
	 * Class:     me_sohamgovande_cardr_platformspecific_WinMSWordInteractor
	 * Method:    getWordWindows
	 * Signature: ()[Ljava/lang/String;
	 */
	JNIEXPORT jobjectArray JNICALL Java_me_sohamgovande_cardr_platformspecific_WinMSWordInteractor_getWordWindows
	(JNIEnv *, jobject);

	/*
	 * Class:     me_sohamgovande_cardr_platformspecific_WinMSWordInteractor
	 * Method:    selectWordWindow
	 * Signature: (Ljava/lang/String;)Z
	 */
	JNIEXPORT jboolean JNICALL Java_me_sohamgovande_cardr_platformspecific_WinMSWordInteractor_selectWordWindow
	(JNIEnv *, jobject, jstring);

	/*
	 * Class:     me_sohamgovande_cardr_platformspecific_WinMSWordInteractor
	 * Method:    setShiftKeyState
	 * Signature: (Z)V
	 */
	JNIEXPORT void JNICALL Java_me_sohamgovande_cardr_platformspecific_WinMSWordInteractor_setShiftKeyState
	(JNIEnv *, jobject, jboolean);

	#ifdef __cplusplus
}
#endif
#endif
